# Generated by Django 5.1.3 on 2024-12-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('opinion', 'Opinion'), ('feature', 'Feature'), ('technology', 'Technology'), ('health', 'Health'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('politics', 'Politics'), ('sports', 'Sports'), ('lifestyle', 'Lifestyle'), ('education', 'Education'), ('environment', 'Environment'), ('culture', 'Culture')], max_length=100),
        ),
    ]
