# Generated by Django 5.1.3 on 2024-12-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Reject'), ('published', 'Published')], default='review', max_length=20),
        ),
    ]
