# Generated by Django 5.1.3 on 2024-12-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_city_country_article_latitude_article_longitude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
