# Generated by Django 5.1.3 on 2024-12-24 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp', 'heic', 'heif', 'ico', 'psd', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(null=True, upload_to='article_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp', 'heic', 'heif', 'ico', 'psd', 'webp', 'avif'])]),
        ),
    ]
